// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wliqkitqqvggwwinugik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsaXFraXRxcXZnZ3d3aW51Z2lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NzMyMDEsImV4cCI6MjA3MzU0OTIwMX0.ue4iRJecYiwmN_Q0_xAjkx2xVGQdZLh6_nhDKMgZ9jY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});